# !bin/bash

CONFIGURE_FILE="configure"
LOG_PREFIX="/sources/.logs/"
LOGS_NAME="AutoconfInstallLogs.log"
LOGS="${LOG_PREFIX}${LOGS_NAME}"


iinstall(){
    conf="./${CONFIGURE_FILE}"
    if [ ! -f $conf ];then
        echo "Can't find ${conf}"
        return 1
    fi

    echo "! Fix a bug generated by Perl." 
    sed '361 s/{/\\{/' -i bin/autoscan.in
    
    echo "Configuring ... ..."
    $conf \
    --prefix=/usr \
    1> /dev/null 2> $LOGS

    echo "Making ... ..."
    make  1>/dev/null 2>>$LOGS

    if [ "${1}" == "--test" ];then
        echo "Expect Testing ... ..."
        make check 1> /dev/null 2>>$LOGS
    fi

    echo "Make-installing ... ..."
    make install 1> /dev/null 2>> $LOGS

    echo "Cleaning Temps ... ..."
    dir=`pwd`;cd ../
    echo "remove ${dir}"
    rm -rf $dir
    pwd
}


main(){
    echo -e "Autoconf\n\r\tApproximate Build Time: 3.2 SBU\n\r\tSpace: 79M\n\r\tVersion: 2.69"
    echo ">>>>> Begin to COMPILE >>>>>"
    iinstall
}


main
